version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  server:
    depends_on:
      - db
    build: ../MedicalTests-server1/
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db

  webapp:
    depends_on:
      - server
    ports:
      - "8080:8080"
    build: .
