version: '3.8'

services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres

  server:
    image: ../MedicalTests-server1
    ports:
      - 3000:3000
    # depends_on:
    #   - db
