version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  server:
    build: ../MedicalTests-server1/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - NODE_ENV=development

  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - server
